# [START app_yaml]
runtime: python39

instance_class: F1

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static

# This handler routes all requests not caught above to your main app. It is
# required here since app.yaml lacks a final handler of this type.
- url: /.*
  script: auto

env_variables:
  
  GOOGLE_APPLICATION_CREDENTIALS: /mindphix-4737c-3b5fd6bae908.json

# [END app_yaml]